name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check:
    name: Nix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix develop --command bash -c 'find -type f -name "*.nix" | xargs nixfmt -c'
      - run: nix flake check
